export const LOAD_PERSONS_SUCCESS = 'LOAD_PERSONS_SUCCESS';
export const LOAD_PERSON_SUCCESS = 'LOAD_PERSON_SUCCESS';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
export const CREATE_PERSON_SUCCESS = 'CREATE_PERSON_SUCCESS';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
